language: cpp

compiler:
  - gcc
  - clang

# Attempt to get the right GCC/Clang versions
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - mkdir build && cd build
  - cmake -DLLVM_TARGETS_TO_BUILD="AVR" .. 
  - make -j3
